### PR TITLE
updated content list to include some more CDN domain names

### LINKED ISSUE #2: Improvement: add CDN networks tagged on bgp.tools
the content list should contain most of the CDN identified on bgp.tools: https://bgp.tools/tags/cdn

### PR DESCRIPTION
**Pull request by Yh010**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=htTGsYF)
Fixes #2

### CODE REVIEW

**Comment by romain-fontugne** [comment]
Thanks. But before merging I'd like to know how you found these domain names or if you have a good reason to add these?
Also please remove the protocol, for example edg.io instead of https://edg.io

Any reason for using www.ovhcloud.com instead of ovh.com?

**Comment by Yh010** [comment]
1)I found these domain names using google search + cdn planet's website and then used traceroute to check for the ip addresses...
2)oh my bad..i forgot to remove the https
3)actually i found both that on cdn planet's  website and checked traceroute for  [www.ovhcloud.com](http://www.ovhcloud.com/) so thought of replacing..both work fine as per my understanding

**Comment by romain-fontugne** [comment]
Thanks. Here are a few improvements:
- from my test I think nsone.com is hosted by cloudflare. We already have cloudflare in the list so we don't need this one.
- I cannot get an ip address for twitchcdn.net so we cannot ping this one. Please remove it.
- cox.com is hosted by incapsula so we don't need this one?
- I cannot ping or traceroute www.rncdn1.com, so maybe we can remove it for now
- from my tests I think that woodynet.net maps to a single place in the world. But I found that  e.nic.ch is working for this company (PCH). So please replace  it by e.nic.ch

**Comment by Yh010** [comment]
@romain-fontugne done

**Comment by romain-fontugne** [comment]
thanks!

**Pull request merged**
